# ############################################################################ #
#
# Copyright (c) 2025 Roberto Sommariva, James Levine, Christian Pfrang.
#
# This file is part of MBM-Flex.
#
# MBM-Flex is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License (https://www.gnu.org/licenses) as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# A copy of the GPLv3 license can be found in the file `LICENSE` at the root of
# the MBM-Flex project.
#
# ############################################################################ #

## ---------------------------------------------------------------------
## R script to calculate exposure metrics from the output of MBM-Flex
##
## Usage:
## 1) set the directory containing the model output (`main.output`) and, if
##    necessary, the directory with the extracted model output (`output.dir`)
## 2) set the name of the csv file to save the calculate metrics (`csvname`)
## 3) source the script from its directory (`MBM-Flex/model/tools/`)
##
## The script calculates the average occupancy of each room, the mean
## and max concentrations, and the fraction of time when the
## concentrations exceed the WHO air quality guidelines -- overall,
## when adults are in the room, and when children are in the
## room. These metrics are saved to csv file for further analysis.
## ---------------------------------------------------------------------

## set the directory containing the model output
main.output <- "20230831_195617_TestSerial"
setwd(paste0("../", main.output))   # the initial working directory is `model_tools/`
                                    # where the script is located

## set the directory containing the extracted model output, generated by
## the `MBM_extractor.py` tool (by default, it is called "extracted_outputs/")
output.dir <- "extracted_outputs/"

## set the filename of csv file to save the calculated metrics
csvname <- paste0(main.output, "_metrics.csv")

## ----------------------------------------

## the `MBM_extractor.py` tool creates one csv file per room, plus one
## for outdoors in the `output.dir` directory
output.files <- list.files(output.dir, pattern=".csv")

# number of rooms
n.room <- length(output.files) - 1

## import model output: indoor values in each room
indoor.df <- data.frame()
for (n in 1:n.room) {
  fname <- paste0(main.output, sprintf("_room%02d",n), ".csv")
  ind.df <- read.csv(paste0(output.dir, fname), header=TRUE)
  ind.df$ROOM <- paste("Room", n, sep=" ")
  indoor.df <- rbind(indoor.df, ind.df)
}

## time in hours
indoor.df$Time <- indoor.df$Time/3600

## ----------------------------------------
## WHO air quality guidelines (2021)
## https://www.who.int/publications/i/item/9789240034228

## units in ug/m3
who.aer <- data.frame(PM25=c(5,15), PM10=c(15,45))
who.gas <- data.frame(O3=c(60,100), NO2=c(10,25), SO2=c(NA,40), CO=c(NA,4000))

who.df <- cbind(who.aer, who.gas)

## ----------------------------------------

## number of timesteps
n.step <- nrow(indoor.df)

## initialize data.frame for the exposure metrics
metrics.df <- data.frame(Species=NA, Metrics=NA)

## calculate exposure metrics in each room
for (n in 1:n.room) {
  room.df <- indoor.df[which(indoor.df$ROOM == paste("Room", n)),]
  metrics.df[,paste("Room", n)] <- NA

  ## number of people in the room
  n.adults <- room.df$adults
  n.children <- room.df$children

  metrics.df[1,1] <- NA
  metrics.df[1,2] <- "Mean number of adults in the room"
  metrics.df[1,n+2] <- mean(n.adults, na.rm=T)

  metrics.df[2,1] <- NA
  metrics.df[2,2] <- "Mean number of children in the room"
  metrics.df[2,n+2] <- mean(n.children, na.rm=T)

  ## select chemical variables (gas-phase species and total suspended particles)
  conc.df <- within(room.df, rm(adults, children))

  ## calculate exposure metrics for each chemical variable
  j <- 3
  for (i in 2:(ncol(conc.df)-1)) {
    var.name <- names(conc.df)[i]

    ## convert gas phase species to ug/m3 assuming standard temperature
    ## and pressure -- according to WHO guidelines 1 ppb = 2 ug/m3
    if (var.name != "tspx") {    ## total suspended particles
      var.df <- conc.df[[i]]*2/2.46e10
    } else {    ## gas-phase species
      var.df <- conc.df[[i]]
    }

    ## select periods when adults/children are in the room
    adults.df <- var.df[which(n.adults>0)]
    children.df <- var.df[which(n.children>0)]

    ## average concentrations
    metrics.df[j,1] <- var.name
    metrics.df[j,2] <- "Mean concentration (ug/m3)"
    metrics.df[j,n+2] <- mean(var.df, na.rm=T)

    metrics.df[j+1,1] <- var.name
    metrics.df[j+1,2] <- "Mean concentration when adults are in the room (ug/m3)"
    metrics.df[j+1,n+2] <- mean(adults.df, na.rm=T)

    metrics.df[j+2,1] <- var.name
    metrics.df[j+2,2] <- "Mean concentration when children are in the room (ug/m3)"
    metrics.df[j+2,n+2] <- mean(children.df, na.rm=T)

    ## max concentrations
    metrics.df[j+3,1] <- var.name
    metrics.df[j+3,2] <- "Max concentration (ug/m3)"
    metrics.df[j+3,n+2] <- max(var.df, na.rm=T)

    metrics.df[j+4,1] <- var.name
    metrics.df[j+4,2] <- "Max concentration when adults are in the room (ug/m3)"
    metrics.df[j+4,n+2] <- max(adults.df, na.rm=T)

    metrics.df[j+5,1] <- var.name
    metrics.df[j+5,2] <- "Max concentration when children are in the room (ug/m3)"
    metrics.df[j+5,n+2] <- max(children.df, na.rm=T)

    ## fractional time when concentrations exceed the WHO guidelines
    if (var.name %in% names(who.df)) {
      who.gl <- who.df[[which(names(who.df)==var.name)]]

      ## overall
      metrics.df[j+6,1] <- var.name
      if (var.name == "O3") {
        metrics.df[j+6,2] <- paste("Time exceeding WHO guideline of", who.gl[1], "ug/m3 (Peak season) (%)")
      } else {
        metrics.df[j+6,2] <- paste("Time exceeding WHO guideline of", who.gl[1], "ug/m3 (Annual) (%)")
      }
      metrics.df[j+6,n+2] <- 100*length(which(var.df > who.gl[1]))/n.step

      metrics.df[j+7,1] <- var.name
      if (var.name == "O3") {
        metrics.df[j+7,2] <- paste("Time exceeding WHO guideline of", who.gl[2], "ug/m3 (8-hour) (%)")
      } else {
        metrics.df[j+7,2] <- paste("Time exceeding WHO guideline of", who.gl[2], "ug/m3 (24-hour) (%)")
      }
      metrics.df[j+7,n+2] <- 100*length(which(var.df > who.gl[2]))/n.step

      ## with adults in the room
      metrics.df[j+8,1] <- var.name
      if (var.name == "O3") {
        metrics.df[j+8,2] <- paste("Time exceeding WHO guideline of", who.gl[1], "ug/m3 when adults are in the room (Peak season) (%)")
      } else {
        metrics.df[j+8,2] <- paste("Time exceeding WHO guideline of", who.gl[1], "ug/m3 when adults are in the room (Annual) (%)")
      }
      metrics.df[j+8,n+2] <- 100*length(which(adults.df > who.gl[1]))/n.step

      metrics.df[j+9,1] <- var.name
      if (var.name == "O3") {
        metrics.df[j+9,2] <- paste("Time exceeding WHO guideline of", who.gl[2], "ug/m3 when adults are in the room (8-hour) (%)")
      } else {
        metrics.df[j+9,2] <- paste("Time exceeding WHO guideline of", who.gl[2], "ug/m3 when adults are in the rooms (24-hour) (%)")
      }
      metrics.df[j+9,n+2] <- 100*length(which(adults.df > who.gl[2]))/n.step

      ## with children in the room
      metrics.df[j+10,1] <- var.name
      if (var.name == "O3") {
        metrics.df[j+10,2] <- paste("Time exceeding WHO guideline of", who.gl[1], "ug/m3 when children are in the room (Peak season) (%)")
      } else {
        metrics.df[j+10,2] <- paste("Time exceeding WHO guideline of", who.gl[1], "ug/m3 when children are in the room (Annual) (%)")
      }
      metrics.df[j+10,n+2] <- 100*length(which(children.df > who.gl[1]))/n.step

      metrics.df[j+11,1] <- var.name
      if (var.name == "O3") {
        metrics.df[j+11,2] <- paste("Time exceeding WHO guideline of", who.gl[2], "ug/m3 when children are in the room (8-hour) (%)")
      } else {
        metrics.df[j+11,2] <- paste("Time exceeding WHO guideline of", who.gl[2], "ug/m3 when children are in the room (24-hour) (%)")
      }
      metrics.df[j+11,n+2] <- 100*length(which(children.df > who.gl[2]))/n.step

      j <- j + 12
    } else {
      j <- j + 6
    }
  }
}

## output exposure metrics to csv file
writeLines(paste("Exposure metrics from MBM-Flex model run,", main.output), csvname)
write.table(metrics.df, csvname, sep=",", row.names=F, col.names=T, append=T)

## return to MBM-Flex directory
cat("\n*** Exposure metrics saved to", paste0(main.output, "/", csvname), "***\n")
setwd("../model_tools/")
